export const ITEMS_AMOUNT = ['Any', '1-3', '4-7', '8-12', '13-20'];

// export const LANGUAGES = [
//   'Afrikaans',
//   'Albanian',
//   'Arabic',
//   'Armenian',
//   'Bengali',
//   'Bosnian',
//   'Bulgarian',
//   'Catalan',
//   'Chinese (Simplified)',
//   'Chinese (Traditional)',
//   'Croatian',
//   'Czech',
//   'Danish',
//   'Dutch',
//   'English',
//   'Estonian',
//   'Finnish',
//   'French',
//   'Georgian',
//   'German',
//   'Greek',
//   'Gujarati',
//   'Hebrew',
//   'Hindi',
//   'Hungarian',
//   'Icelandic',
//   'Indonesian',
//   'Italian',
//   'Japanese',
//   'Kannada',
//   'Kazakh',
//   'Korean',
//   'Latvian',
//   'Lithuanian',
//   'Macedonian',
//   'Malay',
//   'Malayalam',
//   'Marathi',
//   'Mongolian',
//   'Norwegian',
//   'Persian',
//   'Polish',
//   'Portuguese',
//   'Punjabi',
//   'Romanian',
//   'Russian',
//   'Serbian',
//   'Sinhala',
//   'Slovak',
//   'Slovenian',
//   'Spanish',
//   'Swahili',
//   'Swedish',
//   'Tamil',
//   'Telugu',
//   'Thai',
//   'Turkish',
//   'Ukrainian',
//   'Urdu',
//   'Uzbek',
//   'Vietnamese',
//   'Welsh',
//   'Zulu',
// ];

export enum LANGUAGES {
  English = 'English',
  Spanish = 'Spanish',
  French = 'French',
  German = 'German',
  Chinese = 'Chinese',
  Russian = 'Russian',
  Japanese = 'Japanese',
  Korean = 'Korean',
  Italian = 'Italian',
  Portuguese = 'Portuguese',
  Hindi = 'Hindi',
  Arabic = 'Arabic',
  Turkish = 'Turkish',
  Ukrainian = 'Ukrainian',
  Kazakh = 'Kazakh',
  Dutch = 'Dutch',
}
